package com.mricotta.circuitbreaker.inventory.mapper;

import com.mricotta.circuitbreaker.inventory.dto.CreateInventoryItemRequest;
import com.mricotta.circuitbreaker.inventory.dto.InventoryItemResponse;
import com.mricotta.circuitbreaker.inventory.entity.InventoryItem;
import java.util.List;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;

@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
public interface InventoryItemMapper {

    InventoryItemResponse toDto(InventoryItem item);

    List<InventoryItemResponse> toDtoList(List<InventoryItem> items);

    /** The id is generated by the database and {@code updatedAt} by Hibernate on insert. */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    InventoryItem toEntity(CreateInventoryItemRequest request);
}
